// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhjgvffnvczzphfjghim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoamd2ZmZudmN6enBoZmpnaGltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDM0MzEsImV4cCI6MjA2OTM3OTQzMX0.exu_FgWLwYdt8KfKGvWH2jXp0qlHlkoefc-qgyNwCQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});